version: '3.7'

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${POSTGRESQL_USER}
        POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
        PGDATA: /var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start"]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PW}
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      KC_HOSTNAME: ${HOSTNAME}
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8070:8080
    healthcheck:
      test: ["CMD-SHELL", "curl https://staging.sse.uni-hildesheim.de:8443/health/ready --fail"]
      #start_period: 30s
      interval: 20s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
        
  registry:
    image: ghcr.io/e-learning-by-sse/infrastructure-registry:1
    container_name: infrastructure-registry
    image: ghcr.io/e-learning-by-sse/infrastructure-registry:latest
    restart: unless-stopped
    environment:
      EUREKA_INSTANCE_HOSTNAME: ${HOSTNAME}
      EUREKA-ZONE: http://infrastructure-registry:8761/eureka
      SPRING_APPLICATION_NAME: registry
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: 'true'
    volumes:
      - ./registry-config.yml:/workspace/application-prod.yml

  gateway:
    image: ghcr.io/e-learning-by-sse/infrastructure-gateway:latest
    restart: unless-stopped
    environment:
      GW_EUREKA_IP: http://infrastructure-registry:8761/eureka
      GW_OIDC_ISSUER: http://${HOSTNAME}:8080
      GW_OIDC_CLIENTID: ${GW_OIDC_CLIENTID}
      GW_OIDC_SECRET: ${GW_OIDC_SECRET}
      SPRING_PROFILES_ACTIVE: docker,prod
    volumes:
      - ./gateway-config.yml:/workspace/application-prod.yml
    ports: 
      - 8090:8080
    depends_on:
      registry:
        condition: service_started
      keycloak:
        condition: service_healthy